// sv-frontend/src/routes/RelationshipTypeEditor.svelte
<script lang="ts">
  import { RelationshipType } from '../models/PersonRelationship';
  import { Container, Row, Col, Input, Button, ListGroup, ListGroupItem } from '@sveltestrap/sveltestrap';
  import { onMount } from 'svelte';

  let sourceVal = $state('');
  let targetVal = $state('');
  let relationshipTypes: RelationshipType[] = $state([]);

  onMount(async () => {
    relationshipTypes = await RelationshipType.loadFromIndexedDB();
  });

  async function addRelationshipType() {
    if (sourceVal) {
      const newRelationshipType = RelationshipType.create(
        sourceVal,
        targetVal || null
      );
      relationshipTypes = [...relationshipTypes, newRelationshipType];
      await newRelationshipType.saveToIndexedDB();
      sourceVal = '';
      targetVal = '';
    }
  }

  async function deleteRelationshipType(idx: number) {
    const rt = relationshipTypes[idx];
    relationshipTypes = relationshipTypes.filter((_, i) => i !== idx);
    await RelationshipType.deleteFromIndexedDB(rt.id);
  }
</script>

<Container>
  <Row class="align-items-end mb-4">
    <Col>
      <label class="form-label" for="rtSource">关系类型</label>
      <Input id="rtSource" type="text" placeholder="关系类型" bind:value={sourceVal} />
    </Col>
    <Col md="4">
      <label class="form-label" for="rtTarget">（选填）关系类型</label>
      <Input id="rtTarget" type="text" placeholder="选填" bind:value={targetVal} />
    </Col>
    <Col xs="auto">
      <Button color="primary" onclick={addRelationshipType}>
        <i class="bi bi-plus-lg"></i> 添加
      </Button>
    </Col>
  </Row>

  <ListGroup flush>
    {#each relationshipTypes as rt, idx (rt.id)}
      <ListGroupItem>
        <div class="d-flex justify-content-between align-items-center">
          <span>{rt.name}</span>
          <Button color="light" size="sm" onclick={() => deleteRelationshipType(idx)}>
            <i class="bi bi-trash"></i>
          </Button>
        </div>
      </ListGroupItem>
    {/each}
    {#if relationshipTypes.length === 0}
      <ListGroupItem class="text-center text-muted py-5">
        暂无关系类型
      </ListGroupItem>
    {/if}
  </ListGroup>
</Container>

// frontend/src/components/RelationshipTypeEditor.vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <v-text-field density="compact" v-model="relationshipType.source" label="关系类型"></v-text-field>
      </v-col>
      <v-col cols="4">
        <v-text-field density="compact" v-model="relationshipType.target" label="（选填）关系类型"></v-text-field>
      </v-col>
      <v-col cols="auto">
        <v-btn @click="addRelationshipType">添加</v-btn>
      </v-col>
    </v-row>
    <v-list>
      <v-list-item v-for="(relationshipType, index) in relationshipTypes" :key="index">
        <v-row>
          <v-col>
            <v-list-item-title>{{ relationshipType.name }}</v-list-item-title> </v-col>
          <v-col cols="auto">
            <v-list-item-action>
              <v-btn variant="text" @click="deleteRelationshipType(index)">
                <v-icon>mdi-delete</v-icon>
              </v-btn>
            </v-list-item-action>
          </v-col>
        </v-row>
      </v-list-item>
    </v-list>
  </v-container>
</template>

<script>
import { RelationshipType } from '../models/PersonRelationship';

export default {
  data() {
    return {
      relationshipType: {
        source: '',
        target: '',
      },
      relationshipTypes: [],
    };
  },
  async created() {
    this.relationshipTypes = await RelationshipType.loadFromIndexedDB();
  },
  methods: {
    async addRelationshipType() {
      if (this.relationshipType.source) {
        const newRelationshipType = RelationshipType.create(
          this.relationshipType.source,
          this.relationshipType.target || null
        );
        this.relationshipTypes.push(newRelationshipType);
        await newRelationshipType.saveToIndexedDB();
        this.relationshipType = { source: '', target: '' };
      }
    },
    async deleteRelationshipType(index) {
      const relationshipType = this.relationshipTypes.splice(index, 1)[0];
      await RelationshipType.deleteFromIndexedDB(relationshipType.id);
    }
  }
};
</script>

<style scoped></style>
