// frontend/src/components/GroupEditor.vue
<template>
    <v-dialog v-model="dialog" max-width="600px">
        <v-card>
            <v-card-title>
                <span class="headline">编辑群组</span>
            </v-card-title>
            <v-card-text>
                <v-form ref="form">
                    <v-select v-model="selectedMembers" :items="people" item-title="name" item-value="id" label="包含成员"
                        multiple chips clearable :rules="[membersRule]"></v-select>
                </v-form>
            </v-card-text>
            <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn color="blue darken-1" text @click="closeDialog">取消</v-btn>
                <v-btn color="blue darken-1" text @click="saveGroup">保存</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

<script>
import { GroupNode, Person } from '../models/PersonRelationship';

export default {
    props: {
        people: Array,
    },
    data() {
        return {
            dialog: false,
            selectedMembers: [],
            group: null,
        };
    },
    methods: {
        openDialog(group) {
            this.selectedMembers = group ? group.members.map(member => member.id) : [];
            this.group = group;
            this.dialog = true;
        },
        closeDialog() {
            this.dialog = false;
        },
        saveGroup() {
            if (this.$refs.form.validate()) {
                const members = this.people.filter(person => this.selectedMembers.includes(person.id));
                if (members.length < 2) {
                    this.$emit('error', '群组至少包含两名成员');
                    return;
                }
                const updatedGroup = new GroupNode(this.group.id, members, this.group.relationshipType);
                updatedGroup.saveToIndexedDB();
                this.$emit('group-updated', updatedGroup);
                this.closeDialog();
            }
        },
        membersRule(value) {
            return value.length >= 2 || '群组至少包含两名成员';
        }
    }
};
</script>

// sv-frontend/src/components/GroupEditor.svelte
<script lang="ts">
  import { GroupNode, Person } from '../models/PersonRelationship';
  import { Modal, ModalHeader, ModalBody, ModalFooter, Button, FormGroup, Label } from '@sveltestrap/sveltestrap';

  interface Props {
    open: boolean;
    people: Person[];
    group: GroupNode | null;
    onGroupUpdated: (group: GroupNode) => void;
  }

  let { open = $bindable(), people, onGroupUpdated, group }: Props = $props();

  let selectedMembers: string[] = $state([]);
  let memberError = $state('');

  $effect(() => {
    if (open && group) {
      selectedMembers = group.members.map(member => member.id);
    }
  });

  function closeDialog() {
    open = false;
    selectedMembers = [];
    memberError = '';
  }

  function saveGroup() {
    if (selectedMembers.length < 2) {
      memberError = '群组至少包含两名成员';
      return;
    }
    const members = people.filter(p => selectedMembers.includes(p.id));
    if (group) {
      const updatedGroup = new GroupNode(group.id, members, group.relationshipType);
      updatedGroup.saveToIndexedDB();
      onGroupUpdated(updatedGroup);
    }
    closeDialog();
  }

  function toggleMember(id: string) {
    if (selectedMembers.includes(id)) {
      selectedMembers = selectedMembers.filter(m => m !== id);
    } else {
      selectedMembers = [...selectedMembers, id];
    }
    if (selectedMembers.length >= 2) {
      memberError = '';
    }
  }
</script>

<Modal isOpen={open} toggle={closeDialog}>
  <ModalHeader toggle={closeDialog}>
    编辑群组
  </ModalHeader>
  <ModalBody>
    <FormGroup>
      <Label>包含成员</Label>
      <div class="border rounded p-2" style="max-height: 300px; overflow-y: auto;">
        {#each people as p (p.id)}
          <div class="form-check">
            <input
              class="form-check-input"
              type="checkbox"
              id={`member-${p.id}`}
              checked={selectedMembers.includes(p.id)}
              onchange={() => toggleMember(p.id)}
            />
            <label class="form-check-label" for={`member-${p.id}`}>
              {p.name}
            </label>
          </div>
        {/each}
      </div>
      {#if memberError}
        <div class="invalid-feedback d-block">{memberError}</div>
      {/if}
    </FormGroup>
  </ModalBody>
  <ModalFooter>
    <Button color="secondary" onclick={closeDialog}>取消</Button>
    <Button color="primary" onclick={saveGroup}>保存</Button>
  </ModalFooter>
</Modal>
