// frontend/src/components/PersonList.vue
<template>
  <v-container>
    <v-btn icon class="fab" @click="newPerson" color="primary">
      <v-icon>mdi-plus</v-icon>
    </v-btn>
    <v-dialog v-model="dialog" max-width="600px">
      <v-card>
        <v-card-title>{{ editIndex === -1 ? '添加人员' : '编辑人员' }}</v-card-title>
        <v-card-text>
          <v-form ref="form">
            <v-img v-if="person.thumbnailPhoto && typeof person.thumbnailPhoto === 'string'"
              :src="person.thumbnailPhoto" max-width="200" max-height="200" class="mb-3"></v-img>
            <v-text-field v-model="person.name" label="姓名" required></v-text-field>
            <v-file-input label="照片" @update:modelValue="changePhoto" prepend-icon="mdi-camera"
              accept="image/*"></v-file-input>
            <v-text-field v-model="person.contact" label="联系方式"></v-text-field>
            <v-text-field v-model="person.birthYear" label="出生年份"></v-text-field>
            <v-textarea v-model="person.notes" label="备注"></v-textarea>
          </v-form>
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="blue darken-1" text @click="closeDialog">取消</v-btn>
          <v-btn color="blue darken-1" text @click="savePerson">保存</v-btn>
          <v-btn v-if="editIndex !== -1" color="blue darken-1" text @click="saveAsNewVersion">保存为新版本</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
    <v-dialog v-model="photoDialog" max-width="600px">
      <v-card>
        <v-img :src="originalPhoto" max-width="100%" max-height="100%"></v-img>
      </v-card>
    </v-dialog>
    <v-dialog v-model="historyDialog" max-width="600px">
      <v-card>
        <v-card-title>历史版本</v-card-title>
        <v-card-text>
          <v-row>
            <v-col cols="1">
              <v-btn icon variant="text" @click="previousHistory" :disabled="historyIndex === 0">
                <v-icon>mdi-chevron-left</v-icon>
              </v-btn>
            </v-col>
            <v-col cols="10">
              <v-img v-if="currentHistory.thumbnailPhoto" :src="currentHistory.thumbnailPhoto"
                @click="showOriginalPhoto(currentHistory)" max-width="200" max-height="200" class="mb-3"></v-img>
              <v-list-item-title>{{ currentHistory.name }}</v-list-item-title>
              <v-list-item-subtitle>添加日期：{{ new Date(currentHistory.timestamp).toLocaleDateString()
                }}</v-list-item-subtitle>
              <v-list-item-subtitle>联系方式：{{ currentHistory.contact }}</v-list-item-subtitle>
              <br/>
              <v-list-item-subtitle>备注：
                <div v-html="formatNotes(currentHistory.notes)"></div>
              </v-list-item-subtitle>
            </v-col>
            <v-col cols="1">
              <v-btn icon variant="text" @click="nextHistory" :disabled="historyIndex === personHistory.length - 1">
                <v-icon>mdi-chevron-right</v-icon>
              </v-btn>
            </v-col>
          </v-row>
        </v-card-text>
      </v-card>
    </v-dialog>
    <v-list>
      <v-list-item v-for="(person, index) in people" :key="index" class="hover-item">
        <v-row>
          <v-col cols="auto">
            <v-img :src="person.thumbnailPhoto || defaultPhoto" width="100" height="100"
              @click="showOriginalPhoto(person)"></v-img>
          </v-col>
          <v-col>
            <v-list-item-title>
              <v-icon>mdi-account</v-icon>
              {{ person.name }}
            </v-list-item-title>

            <v-row class="ma-0">
              <v-col class="pa-0" cols="12" sm="4" v-if="person.birthYear">
                <v-list-item-subtitle>
                  <v-icon>mdi-calendar</v-icon>
                  {{ person.birthYear }}
                </v-list-item-subtitle>
              </v-col>
              <v-col class="pa-0" cols="12" sm="4" v-if="person.contact">
                <v-list-item-subtitle>
                  <v-icon>mdi-link</v-icon>
                  {{ person.contact }}
                </v-list-item-subtitle>
              </v-col>
              <v-col class="pa-0" cols="12" sm="4" v-if="person.timestamp">
                <v-list-item-subtitle>
                  <v-icon>mdi-update</v-icon>
                  {{ new Date(person.timestamp).toLocaleDateString() }}
                </v-list-item-subtitle>
              </v-col>
            </v-row>

            <div v-html="formatNotes(person.notes)"></div>
          </v-col>
        </v-row>
        <v-list-item-action class="hover-actions">
          <v-btn v-if="person.histories.length" @click="viewHistory(index)">
            <v-icon>mdi-history</v-icon>
          </v-btn>
          <v-btn @click="editPerson(index)">
            <v-icon>mdi-pencil</v-icon>
          </v-btn>
          <v-btn @click="deletePerson(index)">
            <v-icon>mdi-delete</v-icon>
          </v-btn>
        </v-list-item-action>
      </v-list-item>
    </v-list>
  </v-container>
</template>

<script>
import { Person } from '../models/PersonRelationship';
import { v4 as uuidv4 } from 'uuid';

export default {
  data() {
    return {
      dialog: false,
      editIndex: -1,
      person: null,
      people: [],
      defaultPhoto: './whobody.png',
      photoDialog: false,
      originalPhoto: null,
      historyDialog: false,
      personHistory: [],
      historyIndex: 0,
      currentHistory: {},
      newPhoto: null, // Add a new data property to store the new photo temporarily
    };
  },
  async created() {
    this.people = await Person.loadFromIndexedDB();
  },
  methods: {
    newPerson() {
      this.editIndex = -1;
      this.person = Person.create('', null);
      this.newPhoto = null; // Clear the temporary photo
      this.dialog = true;
    },
    closeDialog() {
      this.dialog = false;
      this.newPhoto = null; // Clear the temporary photo
    },
    editPerson(index) {
      this.editIndex = index;
      this.person = { ...this.people[index] };
      this.newPhoto = null; // Clear the temporary photo
      this.dialog = true;
    },
    async deletePerson(index) {
      const person = this.people.splice(index, 1)[0];
      await Person.deleteFromIndexedDB(person.id);
      if (person.photo) {
        await Person.deleteOriginalPhoto(person.photo);
      }
      for (const history of person.histories) {
        if (history.photo) {
          await Person.deleteOriginalPhoto(history.photo);
        }
      }
    },
    async showOriginalPhoto(person) {
      if (!person.photo) {
        return;
      }
      const blob = await Person.loadOriginalPhoto(person.photo);
      if (blob) {
        this.originalPhoto = URL.createObjectURL(blob);
        this.photoDialog = true;
      }
    },
    async changePhoto(file) {
      const thumbnail = await Person.createThumbnail(file);
      this.person.thumbnailPhoto = thumbnail;
      this.newPhoto = file; // Store the new photo temporarily
    },
    async savePerson() {
      if (this.$refs.form.validate()) {
        if (this.newPhoto && !this.person.photo) {
          this.person.photo = uuidv4(); // Create a new UUID for the original photo
        }
        const newPerson = new Person(
          this.person.id,
          this.person.name,
          this.person.thumbnailPhoto,
          this.person.birthYear,
          this.person.contact,
          this.person.notes,
          this.person.timestamp,
          this.person.histories,
          this.person.photo // Save the photo ID
        );
        if (this.editIndex === -1) {
          this.people.push(newPerson);
        } else {
          this.people.splice(this.editIndex, 1, newPerson);
        }
        await newPerson.saveToIndexedDB();
        if (this.newPhoto) {
          await newPerson.saveOriginalPhoto(this.newPhoto, this.person.photo); // Save the new photo with the UUID
          this.newPhoto = null; // Clear the temporary photo
        }
      }
      this.dialog = false;
    },
    async saveAsNewVersion() {
      if (this.$refs.form.validate()) {
        const previousPerson = this.people[this.editIndex];
        previousPerson.histories = [];
        this.person.histories.unshift(previousPerson);
        if (this.newPhoto) {
          this.person.photo = uuidv4(); // Create a new UUID for the original photo
        } else {
          // force to remove the photo
          // otherwise error if user doesn't select a photo for new version, but edit later, which will overwrite the original photo
          this.person.photo = null;
          this.person.thumbnailPhoto = null;
        }
        const newPerson = new Person(
          this.person.id,
          this.person.name,
          this.person.thumbnailPhoto,
          this.person.birthYear,
          this.person.contact,
          this.person.notes,
          new Date().toISOString(),
          this.person.histories,
          this.person.photo // Save the photo ID
        );
        this.people.splice(this.editIndex, 1, newPerson);
        await newPerson.saveToIndexedDB();
        if (this.newPhoto) {
          await newPerson.saveOriginalPhoto(this.newPhoto, this.person.photo); // Save the new photo with the UUID
          this.newPhoto = null; // Clear the temporary photo
        }
      }
      this.dialog = false;
    },
    async viewHistory(index) {
      const person = this.people[index];
      this.personHistory = person.histories;
      this.historyIndex = 0;
      this.currentHistory = this.personHistory[this.historyIndex];
      this.historyDialog = true;
    },
    previousHistory() {
      if (this.historyIndex > 0) {
        this.historyIndex--;
        this.currentHistory = this.personHistory[this.historyIndex];
      }
    },
    nextHistory() {
      if (this.historyIndex < this.personHistory.length - 1) {
        this.historyIndex++;
        this.currentHistory = this.personHistory[this.historyIndex];
      }
    },
    formatNotes(notes) {
      return notes ? notes.replace(/\n/g, '<br>') : '';
    }
  }
};
</script>

<style scoped>
.v-list-item {
  border-bottom: 1px solid rgba(0, 0, 0, 0.12);
  min-height: 100px;
}

.hover-item {
  position: relative;
}

.hover-actions {
  position: absolute;
  top: 8px;
  right: 8px;
  opacity: 0;
  transition: opacity 0.3s;
}

.hover-item:hover .hover-actions {
  opacity: 1;
}

.fab {
  position: fixed;
  bottom: 72px;
  right: 16px;
  width: 56px;
  height: 56px;
  z-index: 1000;
}
</style>

// sv-frontend/src/routes/PersonList.svelte
<script lang="ts">
  import { Person } from '../models/PersonRelationship';
  import { Container, Button, Input, FormGroup, Label, Modal, ModalHeader, ModalBody, ModalFooter } from '@sveltestrap/sveltestrap';
  import { onMount } from 'svelte';

  let people: Person[] = $state([]);
  let dialog = $state(false);
  let editIndex = $state(-1);
  let person: Person = $state(Person.create('', null));
  let defaultPhoto = './whobody.png';
  let photoDialog = $state(false);
  let originalPhoto = $state('');
  let historyDialog = $state(false);
  let personHistory: Person[] = $state([]);
  let historyIndex = $state(0);
  let currentHistory = $state<Person | null>(null);
  let newPhoto: File | null = $state(null);
  let photoPreview = $state<string | null>(null);
  let formValid = $state(true);
  let nameError = $state('');

  onMount(async () => {
    people = await Person.loadFromIndexedDB();
  });

  function newPerson() {
    editIndex = -1;
    person = Person.create('', null);
    newPhoto = null;
    photoPreview = null;
    nameError = '';
    formValid = true;
    dialog = true;
  }

  function closeDialog() {
    dialog = false;
    newPhoto = null;
    photoPreview = null;
    nameError = '';
  }

  function editPerson(idx: number) {
    editIndex = idx;
    person = new Person(
      people[idx].id,
      people[idx].name,
      people[idx].thumbnailPhoto,
      people[idx].birthYear,
      people[idx].contact,
      people[idx].notes,
      people[idx].timestamp,
      [...people[idx].histories],
      people[idx].photo
    );
    newPhoto = null;
    photoPreview = person.thumbnailPhoto;
    nameError = '';
    formValid = true;
    dialog = true;
  }

  async function deletePerson(idx: number) {
    const p = people.splice(idx, 1)[0];
    await Person.deleteFromIndexedDB(p.id);
    if (p.photo) {
      await Person.deleteOriginalPhoto(p.photo);
    }
    for (const history of p.histories) {
      if (history.photo) {
        await Person.deleteOriginalPhoto(history.photo);
      }
    }
  }

  async function showOriginalPhoto(p: Person) {
    if (!p.photo) return;
    const blob = await Person.loadOriginalPhoto(p.photo);
    if (blob) {
      originalPhoto = URL.createObjectURL(blob);
      photoDialog = true;
    }
  }

  async function changePhoto(e: Event) {
    const input = e.target as HTMLInputElement;
    if (input.files && input.files[0]) {
      const file = input.files[0];
      newPhoto = file;
      const thumbnail = await Person.createThumbnail(file);
      person.thumbnailPhoto = thumbnail;
      photoPreview = thumbnail;
    }
  }

  function validateForm(): boolean {
    if (!person.name.trim()) {
      nameError = '姓名不能为空';
      formValid = false;
      return false;
    }
    nameError = '';
    formValid = true;
    return true;
  }

  async function savePerson() {
    if (!validateForm()) return;

    if (newPhoto && !person.photo) {
      person.photo = crypto.randomUUID();
    }
    const newPerson = new Person(
      person.id,
      person.name,
      person.thumbnailPhoto,
      person.birthYear,
      person.contact,
      person.notes,
      person.timestamp,
      person.histories,
      person.photo
    );
    if (editIndex === -1) {
      people.push(newPerson);
    } else {
      people[editIndex] = newPerson;
    }
    await newPerson.saveToIndexedDB();
    if (newPhoto) {
      await newPerson.saveOriginalPhoto(newPhoto, person.photo!);
      newPhoto = null;
      photoPreview = null;
    }
    dialog = false;
  }

  async function saveAsNewVersion() {
    if (!validateForm()) return;

    const previousPerson = people[editIndex];
    previousPerson.histories = [];
    person.histories = [previousPerson, ...person.histories];
    if (newPhoto) {
      person.photo = crypto.randomUUID();
    } else {
      person.photo = null;
      person.thumbnailPhoto = null;
    }
    const newPerson = new Person(
      person.id,
      person.name,
      person.thumbnailPhoto,
      person.birthYear,
      person.contact,
      person.notes,
      new Date().toISOString(),
      person.histories,
      person.photo
    );
    people[editIndex] = newPerson;
    await newPerson.saveToIndexedDB();
    if (newPhoto) {
      await newPerson.saveOriginalPhoto(newPhoto, person.photo!);
      newPhoto = null;
      photoPreview = null;
    }
    dialog = false;
  }

  function viewHistory(idx: number) {
    const p = people[idx];
    personHistory = p.histories;
    historyIndex = 0;
    currentHistory = personHistory.length > 0 ? personHistory[0] : null;
    historyDialog = true;
  }

  function previousHistory() {
    if (historyIndex > 0) {
      historyIndex--;
      currentHistory = personHistory[historyIndex];
    }
  }

  function nextHistory() {
    if (historyIndex < personHistory.length - 1) {
      historyIndex++;
      currentHistory = personHistory[historyIndex];
    }
  }

  function formatNotes(notes: string): string {
    return notes ? notes.replace(/\n/g, '<br>') : '';
  }
</script>

<Container fluid>
  <Button color="primary" style="position: fixed; bottom: 72px; right: 16px; width: 56px; height: 56px; border-radius: 50%; display: flex; align-items: center; justify-content: center; z-index: 1000; font-size: 24px; padding: 0;" onclick={newPerson}>
    <i class="bi bi-plus-lg"></i>
  </Button>

  <Modal isOpen={dialog} toggle={closeDialog}>
    <ModalHeader toggle={closeDialog}>
      {editIndex === -1 ? '添加人员' : '编辑人员'}
    </ModalHeader>
    <ModalBody>
      {#if photoPreview && typeof photoPreview === 'string'}
        <img src={photoPreview} alt="预览" class="mb-3" style="max-width: 200px; max-height: 200px;" />
      {/if}
      <FormGroup>
        <Label for="personName">姓名</Label>
        <Input
          id="personName"
          type="text"
          value={person.name}
          oninput={(e) => {
            person.name = (e.target as HTMLInputElement).value;
            nameError = '';
            formValid = true;
          }}
          invalid={!!nameError}
        />
        {#if nameError}
          <div class="invalid-feedback d-block">{nameError}</div>
        {/if}
      </FormGroup>
      <FormGroup>
        <Label for="personPhoto">
          <i class="bi bi-camera"></i> 照片
        </Label>
        <Input id="personPhoto" type="file" accept="image/*" onchange={changePhoto} />
      </FormGroup>
      <FormGroup>
        <Label for="personContact">联系方式</Label>
        <Input id="personContact" type="text" bind:value={person.contact} />
      </FormGroup>
      <FormGroup>
        <Label for="personBirthYear">出生年份</Label>
        <Input id="personBirthYear" type="text" bind:value={person.birthYear} />
      </FormGroup>
      <FormGroup>
        <Label for="personNotes">备注</Label>
        <Input id="personNotes" type="textarea" bind:value={person.notes} />
      </FormGroup>
    </ModalBody>
    <ModalFooter>
      <Button color="secondary" onclick={closeDialog}>取消</Button>
      <Button color="primary" onclick={savePerson}>保存</Button>
      {#if editIndex !== -1}
        <Button color="primary" onclick={saveAsNewVersion}>保存为新版本</Button>
      {/if}
    </ModalFooter>
  </Modal>

  <Modal isOpen={photoDialog} toggle={() => photoDialog = false} size="lg">
    <ModalBody>
      <div class="d-flex justify-content-center">
        <img src={originalPhoto} alt="原图" style="max-width: 100%; max-height: 80vh;" />
      </div>
    </ModalBody>
  </Modal>

  <Modal isOpen={historyDialog} toggle={() => historyDialog = false}>
    <ModalHeader toggle={() => historyDialog = false}>
      历史版本
    </ModalHeader>
    <ModalBody>
      {#if currentHistory}
        <div class="d-flex align-items-center">
          <Button color="link" disabled={historyIndex === 0} onclick={previousHistory}>
            <i class="bi bi-chevron-left"></i>
          </Button>
          <div class="flex-grow-1 text-center">
            {#if currentHistory.thumbnailPhoto}
              <button class="img-btn" onclick={() => currentHistory && showOriginalPhoto(currentHistory)}>
                <img
                  src={currentHistory.thumbnailPhoto}
                  alt="历史照片"
                  class="mb-3"
                  style="max-width: 200px; max-height: 200px;"
                />
              </button>
            {/if}
            <div class="fw-bold">{currentHistory.name}</div>
            <div>添加日期：{new Date(currentHistory.timestamp).toLocaleDateString()}</div>
            <div>联系方式：{currentHistory.contact}</div>
            <div>
              备注：
              {@html formatNotes(currentHistory.notes)}
            </div>
          </div>
          <Button color="link" disabled={historyIndex === personHistory.length - 1} onclick={nextHistory}>
            <i class="bi bi-chevron-right"></i>
          </Button>
        </div>
      {/if}
    </ModalBody>
  </Modal>

  <div class="list-group list-group-flush">
    {#each people as p, idx (p.id)}
      <div class="list-group-item hover-item">
        <div class="d-flex">
          <button class="img-btn" onclick={() => showOriginalPhoto(p)}>
          <img
            src={p.thumbnailPhoto || defaultPhoto}
            alt={p.name}
            width="100"
            height="100"
            class="me-3 rounded"
            style="object-fit: cover; cursor: pointer;"
          />
        </button>
          <div class="flex-grow-1">
            <div class="fw-bold">
              <i class="bi bi-person"></i> {p.name}
            </div>
            <div class="d-flex flex-wrap gap-3 mt-1 small text-muted">
              {#if p.birthYear}
                <div><i class="bi bi-calendar"></i> {p.birthYear}</div>
              {/if}
              {#if p.contact}
                <div><i class="bi bi-link"></i> {p.contact}</div>
              {/if}
              {#if p.timestamp}
                <div><i class="bi bi-clock"></i> {new Date(p.timestamp).toLocaleDateString()}</div>
              {/if}
            </div>
            {@html formatNotes(p.notes)}
          </div>
          <div class="hover-actions">
            {#if p.histories.length > 0}
              <Button color="light" size="sm" onclick={() => viewHistory(idx)}>
                <i class="bi bi-clock-history"></i>
              </Button>
            {/if}
            <Button color="light" size="sm" onclick={() => editPerson(idx)}>
              <i class="bi bi-pencil"></i>
            </Button>
            <Button color="light" size="sm" onclick={() => deletePerson(idx)}>
              <i class="bi bi-trash"></i>
            </Button>
          </div>
        </div>
      </div>
    {/each}
    {#if people.length === 0}
      <div class="list-group-item text-center text-muted py-5">
        <i class="bi bi-people" style="font-size: 3rem;"></i>
        <p class="mt-3">暂无人员，点击右下角 + 添加</p>
      </div>
    {/if}
  </div>
</Container>

<style>
  .img-btn {
    background: none;
    border: none;
    padding: 0;
    cursor: pointer;
  }

  .hover-item {
    position: relative;
    border-bottom: 1px solid rgba(0, 0, 0, 0.12);
    min-height: 100px;
  }

  .hover-actions {
    position: absolute;
    top: 8px;
    right: 8px;
    opacity: 0;
    transition: opacity 0.3s;
    display: flex;
    gap: 4px;
  }

  .hover-item:hover .hover-actions {
    opacity: 1;
  }
</style>
